name: build-push

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: lukman31/authdeploy:latest
      - 
        name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
              docker stop projectauth
              docker rm projectauth
              docker rmi lukman31/authdeploy
              docker run --name projectauth --link mysqlbe12 -d -p 8000:8000 -e DB_USER=${{secrets.DB_USER}} -e DB_PWD=${{secrets.DB_PWD}} -e DB_HOST=${{secrets.DB_HOST}}  -e DB_PORT=${{secrets.DB_PORT}}  -e DB_NAME=${{secrets.DB_NAME}} -e JW_SECRET=${{secrets.JW_SECRET}} lukman31/authdeploy



          
 
